In [1]:
%load_ext autoreload
%autoreload 2

In [2]:

%matplotlib widget

### 累計レポート
# 標準ライブラリ
import os
from datetime import datetime, timedelta
from typing import List, Dict, Tuple, Optional, Callable

# サードパーティライブラリ
import polars as pl
import matplotlib.pyplot as plt
import japanize_matplotlib
from matplotlib.ticker import ScalarFormatter
from IPython.display import Markdown, display

# プロジェクト内モジュール
import gamedata as g

In [3]:
df_all = g.load_hard_sales()

ex1 = g.extract_latest(df_all)
ex1

┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ wee ┆ beg ┆ end ┆ rep ┆ per ┆ hw  ┆ uni ┆ adj ┆ yea ┆ mon ┆ mda ┆ wee ┆ del ┆ del ┆ del ┆ del ┆ avg ┆ sum ┆ lau ┆ mak ┆ ful ┆ qua │
│ kly ┆ in_ ┆ _da ┆ ort ┆ iod ┆ --- ┆ ts  ┆ ust ┆ r   ┆ th  ┆ y   ┆ k   ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ _un ┆ _un ┆ nch ┆ er_ ┆ l_n ┆ rte │
│ _id ┆ dat ┆ te  ┆ _da ┆ _da ┆ str ┆ --- ┆ _un ┆ --- ┆ --- ┆ --- ┆ --- ┆ day ┆ wee ┆ mon ┆ yea ┆ its ┆ its ┆ _da ┆ nam ┆ ame ┆ r   │
│ --- ┆ e   ┆ --- ┆ te  ┆ te  ┆     ┆ i64 ┆ its ┆ i16 ┆ i16 ┆ i16 ┆ i16 ┆ --- ┆ k   ┆ th  ┆ r   ┆ --- ┆ --- ┆ te  ┆ e   ┆ --- ┆ --- │
│ str ┆ --- ┆ dat ┆ --- ┆ --- ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ i32 ┆ --- ┆ --- ┆ --- ┆ i64 ┆ i64 ┆ --- ┆ --- ┆ str ┆ str │
│     ┆ dat ┆ e   ┆ dat ┆ i16 ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆ i16 ┆ i16 ┆     ┆     ┆ dat ┆ str ┆     ┆     │
│     ┆ e   ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ NS2 ┆ 59, ┆ 0   ┆ 2,0 ┆ 4   ┆ 5   ┆ 1   ┆ 304 ┆ 43  ┆ 10  ┆ 1   ┆ 8,5 ┆ 5,0 ┆ 202 ┆ Nin ┆ Nin ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 543 ┆     ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 06  ┆ 11, ┆ 5-0 ┆ ten ┆ ten ┆ 6Q2 │
│ 4-0 ┆ 3-3 ┆ 4-0 ┆ 4-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 059 ┆ 6-0 ┆ do  ┆ do  ┆     │
│ 5_N ┆ 0   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆ Swi ┆     │
│ S2  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ NSW ┆ 16, ┆ 0   ┆ 2,0 ┆ 4   ┆ 5   ┆ 1   ┆ 3,3 ┆ 474 ┆ 109 ┆ 9   ┆ 2,3 ┆ 36, ┆ 201 ┆ Nin ┆ Nin ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 342 ┆     ┆ 26  ┆     ┆     ┆     ┆ 20  ┆     ┆     ┆     ┆ 34  ┆ 701 ┆ 7-0 ┆ ten ┆ ten ┆ 6Q2 │
│ 4-0 ┆ 3-3 ┆ 4-0 ┆ 4-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,35 ┆ 3-0 ┆ do  ┆ do  ┆     │
│ 5_N ┆ 0   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆ 3   ┆     ┆ Swi ┆     │
│ SW  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ PS5 ┆ 13, ┆ 0   ┆ 2,0 ┆ 4   ┆ 5   ┆ 1   ┆ 1,9 ┆ 281 ┆ 65  ┆ 6   ┆ 1,9 ┆ 7,5 ┆ 202 ┆ SON ┆ Pla ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 539 ┆     ┆ 26  ┆     ┆     ┆     ┆ 70  ┆     ┆     ┆     ┆ 34  ┆ 00, ┆ 0-1 ┆ Y   ┆ ySt ┆ 6Q2 │
│ 4-0 ┆ 3-3 ┆ 4-0 ┆ 4-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 537 ┆ 1-1 ┆     ┆ ati ┆     │
│ 5_P ┆ 0   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ on5 ┆     │
│ S5  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ XSX ┆ 932 ┆ 0   ┆ 2,0 ┆ 4   ┆ 5   ┆ 1   ┆ 1,9 ┆ 281 ┆ 65  ┆ 6   ┆ 133 ┆ 697 ┆ 202 ┆ Mic ┆ Xbo ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆     ┆     ┆ 26  ┆     ┆     ┆     ┆ 72  ┆     ┆     ┆     ┆     ┆ ,56 ┆ 0-1 ┆ ros ┆ x   ┆ 6Q2 │
│ 4-0 ┆ 3-3 ┆ 4-0 ┆ 4-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆ 1-1 ┆ oft ┆ Ser ┆     │
│ 5_X ┆ 0   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ ies ┆     │
│ SX  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ X|S ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [12]:
hw_summary_df = df_all.sort("hw", "delta_week").unique(subset="hw", keep="last")
ps4_summary_df = hw_summary_df.filter((pl.col("hw") == "PS4") | (pl.col("hw") == "PS3"))
ps4_summary_df.transpose(include_header=True, column_names=ps4_summary_df["hw"].to_list())

┌──────────────┬────────────────┬────────────────┐
│ column       ┆ PS3            ┆ PS4            │
│ ---          ┆ ---            ┆ ---            │
│ str          ┆ str            ┆ str            │
╞══════════════╪════════════════╪════════════════╡
│ weekly_id    ┆ 2015-12-13_PS3 ┆ 2026-03-29_PS4 │
│ begin_date   ┆ 2015-12-07     ┆ 2026-03-23     │
│ end_date     ┆ 2015-12-13     ┆ 2026-03-29     │
│ report_date  ┆ 2015-12-13     ┆ 2026-03-29     │
│ period_date  ┆ 7              ┆ 7              │
│ hw           ┆ PS3            ┆ PS4            │
│ units        ┆ 1903           ┆ 16             │
│ adjust_units ┆ 0              ┆ 0              │
│ year         ┆ 2015           ┆ 2026           │
│ month        ┆ 12             ┆ 3              │
│ mday         ┆ 13             ┆ 29             │
│ week         ┆ 2              ┆ 5              │
│ delta_day    ┆ 3319           ┆ 4418           │
│ delta_week   ┆ 474            ┆ 631            │
│ delta_month  ┆ 109            ┆ 145            │
│ delta_year   ┆ 9              ┆ 12             │
│ avg_units    ┆ 271            ┆ 2              │
│ sum_units    ┆ 10080894       ┆ 9491322        │
│ launch_date  ┆ 2006-11-11     ┆ 2014-02-22     │
│ maker_name   ┆ SONY           ┆ SONY           │
│ full_name    ┆ PlayStation3   ┆ PlayStation4   │
│ quarter      ┆ 2015Q4         ┆ 2026Q1         │
└──────────────┴────────────────┴────────────────┘

In [10]:
ps3_summary_df = hw_summary_df.filter(pl.col("hw") == "PS3")
ps3_summary_df.transpose(include_header=True)

┌──────────────┬────────────────┐
│ column       ┆ column_0       │
│ ---          ┆ ---            │
│ str          ┆ str            │
╞══════════════╪════════════════╡
│ weekly_id    ┆ 2015-12-13_PS3 │
│ begin_date   ┆ 2015-12-07     │
│ end_date     ┆ 2015-12-13     │
│ report_date  ┆ 2015-12-13     │
│ period_date  ┆ 7              │
│ hw           ┆ PS3            │
│ units        ┆ 1903           │
│ adjust_units ┆ 0              │
│ year         ┆ 2015           │
│ month        ┆ 12             │
│ mday         ┆ 13             │
│ week         ┆ 2              │
│ delta_day    ┆ 3319           │
│ delta_week   ┆ 474            │
│ delta_month  ┆ 109            │
│ delta_year   ┆ 9              │
│ avg_units    ┆ 271            │
│ sum_units    ┆ 10080894       │
│ launch_date  ┆ 2006-11-11     │
│ maker_name   ┆ SONY           │
│ full_name    ┆ PlayStation3   │
│ quarter      ┆ 2015Q4         │
└──────────────┴────────────────┘