In [3]:
%load_ext autoreload
%autoreload 2

In [4]:

%matplotlib widget

### 累計レポート
# 標準ライブラリ
import os
from datetime import datetime, timedelta
from typing import List, Dict, Tuple, Optional, Callable

# サードパーティライブラリ
import polars as pl
import polars.selectors as cs
import matplotlib.pyplot as plt
from matplotlib.figure import Figure

import japanize_matplotlib
from matplotlib.ticker import ScalarFormatter
from IPython.display import Markdown, display

# プロジェクト内モジュール
import gamedata as g

In [3]:
df_all = g.load_hard_sales()

In [5]:
def add_weeek_number(df: pl.DataFrame) -> pl.DataFrame:
    if "delta_week" in df.columns:
        df = df.with_columns(
            (pl.col("delta_week") + 1).alias("week_number")
        )
    return df

In [18]:
hard_n = 4800000
df2 = (
    g.extract_week_reached_units(df_all, hard_n).
    sort("delta_week", descending=False).
    head(10).
    select(["full_name", "report_date", "hw", "delta_week", "sum_units"])
)
df3 = (
    add_weeek_number(df2).
    select(["full_name", "report_date", "week_number"])
)
df4 = g.rename_columns(df3)
st = g.style(df4)
display(st)

In [6]:
def chart_reached_unit(n:int) -> pl.DataFrame:
    df = g.load_hard_sales()
    df = (
        g.extract_week_reached_units(df, n).
        sort("delta_week", descending=False).
        head(10)
    )
    df = (add_weeek_number(df).
          select(["hw", "report_date", "week_number", "sum_units"]))
    return df

In [ ]:
def chart_reached_unit2(n:int) -> pl.DataFrame:
    df = g.load_hard_sales()
    d2 = g.extract_week_reached_units(df, n).sort_values('delta_week', ascending=True).head(10)
    d3 = d2[['report_date', 'hw', 'delta_week', 'sum_units']].copy()
    d3 = d3.copy().assign(delta_week=lambda x: x['delta_week'] + 1)
    d3.reset_index(drop=True, inplace=True)
    d3.index += 1
    return d3

# 普及速度ダッシュボード

### XX週目の値比較

In [5]:

g.chart_delta_week(28)

AttributeError: module 'gamedata' has no attribute 'chart_delta_week'

## 100万台

In [20]:
g.chart_reached_unit(1_000_000)

┌─────┬─────────────┬─────────────┬───────────┐
│ hw  ┆ report_date ┆ week_number ┆ sum_units │
│ --- ┆ ---         ┆ ---         ┆ ---       │
│ str ┆ date        ┆ i32         ┆ i64       │
╞═════╪═════════════╪═════════════╪═══════════╡
│ GBA ┆ 2001-04-08  ┆ 3           ┆ 1,132,611 │
│ NS2 ┆ 2025-06-22  ┆ 3           ┆ 1,008,663 │
│ DS  ┆ 2004-12-26  ┆ 4           ┆ 1,056,428 │
│ PS2 ┆ 2000-04-02  ┆ 5           ┆ 1,134,882 │
│ Wii ┆ 2007-01-07  ┆ 6           ┆ 1,135,671 │
│ 3DS ┆ 2011-05-22  ┆ 13          ┆ 1,008,237 │
│ PSP ┆ 2005-03-13  ┆ 14          ┆ 1,002,827 │
│ GC  ┆ 2002-01-06  ┆ 17          ┆ 1,064,457 │
│ NSW ┆ 2017-06-25  ┆ 17          ┆ 1,016,473 │
│ PKS ┆ 1999-07-18  ┆ 26          ┆ 1,044,582 │
└─────┴─────────────┴─────────────┴───────────┘

## 200万台

In [19]:
chart_reached_unit(2_000_000)

┌─────┬─────────────┬─────────────┬───────────┐
│ hw  ┆ report_date ┆ week_number ┆ sum_units │
│ --- ┆ ---         ┆ ---         ┆ ---       │
│ str ┆ date        ┆ i32         ┆ i64       │
╞═════╪═════════════╪═════════════╪═══════════╡
│ GBA ┆ 2001-06-17  ┆ 13          ┆ 2,043,244 │
│ NS2 ┆ 2025-09-14  ┆ 15          ┆ 2,024,761 │
│ PS2 ┆ 2000-06-25  ┆ 17          ┆ 2,008,755 │
│ Wii ┆ 2007-04-08  ┆ 19          ┆ 2,038,951 │
│ DS  ┆ 2005-05-01  ┆ 22          ┆ 2,037,178 │
│ 3DS ┆ 2011-10-09  ┆ 33          ┆ 2,024,869 │
│ NSW ┆ 2017-10-29  ┆ 35          ┆ 2,041,221 │
│ PKS ┆ 1999-10-10  ┆ 38          ┆ 2,051,852 │
│ PSP ┆ 2005-11-06  ┆ 48          ┆ 2,003,979 │
│ GC  ┆ 2003-01-05  ┆ 69          ┆ 2,032,355 │
└─────┴─────────────┴─────────────┴───────────┘

## 300万台

In [9]:
chart_reached_unit(3_000_000)

┌─────┬─────────────┬─────────────┬───────────┐
│ hw  ┆ report_date ┆ week_number ┆ sum_units │
│ --- ┆ ---         ┆ ---         ┆ ---       │
│ str ┆ date        ┆ i32         ┆ i64       │
╞═════╪═════════════╪═════════════╪═══════════╡
│ GBA ┆ 2001-09-09  ┆ 25          ┆ 3,051,291 │
│ NS2 ┆ 2025-12-07  ┆ 27          ┆ 3,171,833 │
│ Wii ┆ 2007-07-15  ┆ 33          ┆ 3,014,828 │
│ PS2 ┆ 2000-12-17  ┆ 42          ┆ 3,005,742 │
│ DS  ┆ 2005-09-18  ┆ 42          ┆ 3,015,412 │
│ 3DS ┆ 2011-12-11  ┆ 42          ┆ 3,233,571 │
│ NSW ┆ 2017-12-24  ┆ 43          ┆ 3,291,903 │
│ PKS ┆ 2000-01-23  ┆ 53          ┆ 3,011,335 │
│ PSP ┆ 2006-02-26  ┆ 64          ┆ 3,021,494 │
│ GC  ┆ 2004-01-04  ┆ 121         ┆ 3,115,532 │
└─────┴─────────────┴─────────────┴───────────┘

In [8]:
chart_reached_unit(3_170_000)

   report_date   hw  delta_week  sum_units
1   2001-09-23  GBA          27    3170501
2   2025-12-07  NS2          27    3171833
3   2007-08-05  Wii          36    3223673
4   2011-12-11  3DS          42    3233571
5   2017-12-24  NSW          43    3291903
6   2001-01-07  PS2          45    3179829
7   2005-10-16   DS          46    3216812
8   2000-03-12  PKS          60    3180904
9   2006-03-26  PSP          68    3174196
10  2004-01-25   GC         124    3180437

## 400万台

In [9]:
chart_reached_unit(4_000_000)

   report_date   hw  delta_week  sum_units
1   2026-01-11  NS2          32    4097905
2   2001-12-30  GBA          41    4245686
3   2011-12-25  3DS          44    4132038
4   2005-12-11   DS          54    4102277
5   2007-12-09  Wii          54    4025012
6   2018-03-25  NSW          56    4037144
7   2001-06-03  PS2          66    4019182
8   2006-09-24  PSP          94    4006979
9   2023-07-30  PS5         142    4046566
10  2017-01-08  PS4         151    4089279

## 500万台

In [18]:
display(g.style(g.rename_columns(g.rename_hw(g.chart_reached_unit(5_000_000)))))

## 600万台

## 700万台

## 1000万台

In [10]:
chart_reached_unit(10_000_000)

  report_date   hw  delta_week  sum_units
1  2006-08-13   DS          89   10103791
2  2013-01-06  3DS          98   10064491
3  2003-08-10  GBA         125   10053173
4  2019-11-17  NSW         142   10065815
5  2002-12-29  PS2         148   10099415
6  2010-02-28  Wii         170   10009736
7  2008-08-24  PSP         194   10005546
8  2015-04-12  PS3         440   10000545

In [11]:
chart_reached_unit(20_000_000)

  report_date   hw  delta_week  sum_units
1  2007-11-25   DS         156   20051787
2  2021-05-30  NSW         222   20018296
3  2016-01-17  3DS         256   20029293
4  2007-08-05  PS2         388   20010665

In [12]:
chart_reached_unit(30_000_000)

  report_date   hw  delta_week  sum_units
1  2010-03-21   DS         277   30030199
2  2023-07-30  NSW         335   30073527

In [13]:
chart_reached_unit(35_000_000)

  report_date   hw  delta_week  sum_units
1  2025-01-05  NSW         410   35005506